"""Order-backed identities, canonical products and stock-safe confirmation."""
import os
import pytest

from test_stock_sync_mapping import mapped_system, scan, confirm
from stock_sync_fixtures import system
from stock_sync_common import dumps
import stock_sync_identity as identity
import stock_sync_mapping as mapping


@pytest.fixture
def identities(mapped_system):
    s = mapped_system
    s.sql('ALTER TABLE inv_skus ADD COLUMN notes TEXT')
    s.sql('CREATE TABLE brands(id INTEGER PRIMARY KEY,name TEXT,aliases TEXT)')
    s.sql('CREATE TABLE series(id INTEGER PRIMARY KEY,brand_id INTEGER,name TEXT)')
    s.sql('CREATE TABLE orders(source TEXT,line_items TEXT,date_created TEXT)')
    s.sql("INSERT INTO brands VALUES(7,'Hifancy','[]')")
    if os.getenv('STOCK_SYNC_TEST_POSTGRES') == '1':
        s.sql('ALTER TABLE inv_skus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 100000)')
        s.sql('ALTER TABLE series ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 100000)')
    s.sql('CREATE UNIQUE INDEX identity_sku_code ON inv_skus(sku_code)')
    return s


def product(s, site, *, flavor='Cola Ice', name=None, sku=None):
    url = 'https://reference.test' if site == 1 else 'https://target.test'
    pid = site*1000+1
    p = s.http.products[f'{url}/wp-json/wc/v3/products/{pid}']
    p.update(name=name or f'Hifancy Dream 45000 Puffs - {flavor}',
             sku=sku if sku is not None else 'HIFANCY-DREAM-45000-PUFFS-'+flavor.replace(' ','-').upper())
    return p


def order(s, site, p, *, name=None, sku=None, variant=0):
    source = {1:'https://reference.test',2:'https://target.test',3:'https://outside.test'}[site]
    item = {'product_id':p['id'], 'variation_id':variant, 'name':name or p['name'], 'sku':p['sku'] if sku is None else sku,
            'private_customer_field':'MUST NOT LEAVE ORDER READER'}
    s.sql('INSERT INTO orders VALUES(?,?,?)', (source,dumps([item]),'2026-09-17T10:00:00'))


def auto_payload(report, ids=None):
    selected = [i for i in report['items'] if i.get('certain') and i['writable'] and i['state'] in ('new','align','suggested') and (ids is None or i['id'] in ids)]
    return {'reviewed':True,'reason':'Reviewed automatic product identity',
            'items':[{'id':i['id'],'sku_id':i['proposed_sku_id'],'qty_per_item':i['qty_per_item'],
                      **({'create_sku':True} if i['state']=='new' else {})} for i in selected]}


def test_new_product_shared_across_sites_has_one_master_and_no_stock(identities):
    s=identities
    for sid in (1,2):
        p=product(s,sid);order(s,sid,p)
    s.sql('DELETE FROM inv_site_sku_map WHERE wc_product_id IN (1001,2001)')
    report=scan(s);chosen=[i for i in report['items'] if i['id'] in ('1:1001:0','2:2001:0')]
    assert all(i['state']=='new' and i['certain'] for i in chosen)
    assert chosen[0]['new_sku']['sku_code']==chosen[1]['new_sku']['sku_code']
    assert len(s.sql('SELECT * FROM inv_skus'))==3
    body=auto_payload(report,{i['id'] for i in chosen})
    r=s.call('/mapping-scans/'+report['id']+'/confirm','POST',body);assert r.status_code==202
    s.work();result=s.call('/mapping-confirmations/'+r.get_json()['id']).get_json()
    assert result['complete'], result
    masters=s.sql("SELECT * FROM inv_skus WHERE sku_code LIKE 'CAT-%'");assert len(masters)==1
    sku=masters[0]
    assert sku['brand_id']==7 and sku['series_id'] and sku['puff_count']==45000 and sku['flavor']=='Cola Ice'
    assert s.sql('SELECT COUNT(*) AS n FROM inv_site_sku_map WHERE sku_id=?',(sku['id'],))[0]['n']==2
    assert s.sql('SELECT * FROM oms_sku_warehouses WHERE sku_id=?',(sku['id'],))[0]['warehouse_id']==1
    assert not s.sql('SELECT * FROM inv_stock WHERE sku_id=?',(sku['id'],)) and not s.http.puts
    assert s.call('/mapping-scans/'+report['id']+'/confirm','POST',body).get_json()==r.get_json()
    c=s.connect();mapping.apply(c,r.get_json()['id'],s.woo);c.close()
    assert len(s.sql("SELECT * FROM inv_skus WHERE sku_code LIKE 'CAT-%'"))==1
    # The resulting identities can be used by the actual cross-site planner.
    plan=s.plan('reference_status');assert any(i['decision']=='change' and i['sku_id']==sku['id'] for i in plan['items'])


def test_order_product_ids_recover_a_catalog_name_without_reading_customer_fields(identities):
    s=identities;p=product(s,2,name='Catalogue entry',sku='opaque-code')
    order(s,2,p,name='Hifancy Dream 45000 Puffs - Cola Ice')
    item=next(i for i in scan(s)['items'] if i['id']=='2:2001:0')
    assert item['state']=='new' and item['product_identity']['model']=='Dream'
    assert '订单' in item['explanation'] and 'order_evidence' not in item
    assert 'MUST NOT LEAVE' not in dumps(item)


def test_readable_sku_recovers_missing_title_without_orders(identities):
    s=identities;product(s,2,name='Catalogue entry')
    item=next(i for i in scan(s)['items'] if i['id']=='2:2001:0')
    assert item['state']=='new' and item['product_identity']['flavor_key']=='cola ice'


def test_cross_site_exact_order_sku_resolves_marketing_title(identities):
    s=identities;p=product(s,1,sku='opaque-shared-code');order(s,1,p)
    product(s,2,name='Catalogue label',sku=p['sku'])
    item=next(i for i in scan(s)['items'] if i['id']=='2:2001:0')
    assert item['state']=='new' and item['evidence_label'].startswith('订单')


def test_shared_reference_does_not_grant_access_to_its_orders(identities):
    s=identities;p=product(s,1,sku='opaque-shared-code');order(s,1,p)
    product(s,2,name='Catalogue label',sku=p['sku'])
    s.sql('UPDATE users SET can_manage_inventory=TRUE WHERE id=2')
    s.sql("INSERT INTO stock_sync_reference_sites VALUES(1,TRUE,1,1,'2026-09-17')")
    s.login(2);report=scan(s)
    item=next(i for i in report['items'] if i['id']=='2:2001:0')
    assert item['state']=='unmatched' and report['identity_summary']['order_products']==0


@pytest.mark.parametrize('kind',['order_flavor','sku_model','unknown_variant','different_strength'])
def test_conflicting_evidence_stays_manual(identities,kind):
    s=identities;p=product(s,2)
    if kind=='order_flavor':order(s,2,p,name='Hifancy Dream 45000 Puffs - Strawberry Ice',sku='')
    elif kind=='sku_model':p['sku']='HIFANCY-SPACE-45000-PUFFS-COLA-ICE'
    elif kind=='unknown_variant':p['attributes']=[{'name':'Color','option':'Blue'}]
    else:
        product(s,1,name='Hifancy Dream 45000 Puffs - Cola Ice',sku='')
        p.update(name='Hifancy Dream 45000 Puffs - Cola Ice',attributes=[{'name':'Nicotine','option':'20mg'}])
        s.sql("UPDATE inv_skus SET name='Hifancy Dream 45000 Puffs - Cola Ice',brand_id=7,puff_count=45000,flavor='Cola Ice' WHERE id=1")
        s.http.products['https://reference.test/wp-json/wc/v3/products/1001']['attributes']=[{'name':'Nicotine','option':'0mg'}]
    item=next(i for i in scan(s)['items'] if i['id']=='2:2001:0')
    if kind=='unknown_variant':assert not item.get('new_sku')
    else:assert item['state']=='review' and not item['certain']


def test_manual_partner_duplicate_alignment_preserves_skus_and_history(identities):
    s=identities
    for k in (1,2):s.sql('UPDATE inv_skus SET sku_code=?,name=? WHERE id=?',(f'MANUAL-PL-{k}-1-1','Hifancy Dream 45000 Puffs - Cola Ice',k))
    product(s,1);product(s,2)
    s.sql('UPDATE inv_site_sku_map SET sku_id=2 WHERE site_id=1 AND wc_product_id=1001')
    s.sql('CREATE TABLE historical_fulfillment(id INTEGER PRIMARY KEY,sku_id INTEGER)')
    s.sql('INSERT INTO historical_fulfillment VALUES(1,2)')
    report=scan(s);item=next(i for i in report['items'] if i['id']=='1:1001:0')
    assert item['state']=='align' and item['proposed_sku_id']==1
    result=confirm(s,report,auto_payload(report,{'1:1001:0','2:2001:0'}));assert result['complete'],result
    assert s.sql('SELECT sku_id FROM inv_site_sku_map WHERE wc_product_id=1001')[0]['sku_id']==1
    assert s.sql('SELECT sku_id FROM historical_fulfillment')[0]['sku_id']==2
    assert len(s.sql('SELECT * FROM inv_skus'))==3 and not s.http.puts


def test_real_stock_duplicate_cannot_be_automatically_aligned(identities):
    s=identities
    for k in (1,2):s.sql('UPDATE inv_skus SET sku_code=?,name=? WHERE id=?',(f'MANUAL-PL-{k}-1-1','Hifancy Dream 45000 Puffs - Cola Ice',k))
    s.sql('INSERT INTO inv_stock VALUES(1,2,10,0)');product(s,2)
    item=next(i for i in scan(s)['items'] if i['id']=='2:2001:0')
    assert item['state']=='review' and not item['certain']


def test_new_identity_requires_explicit_selection_and_original_proposal(identities):
    s=identities;product(s,2);report=scan(s)
    body=auto_payload(report,{'2:2001:0'});body['items'][0]['sku_id']=99999
    assert s.call('/mapping-scans/'+report['id']+'/confirm','POST',body).status_code==400
    body=auto_payload(report,{'2:2001:0'});body['items'][0]['new_sku']={'sku_code':'ATTACK','warehouse_id':2}
    result=confirm(s,report,body);assert result['complete']
    assert not s.sql("SELECT * FROM inv_skus WHERE sku_code='ATTACK'")
    assert not s.sql('SELECT * FROM inv_stock')


def test_changed_order_proof_blocks_confirmation_atomically(identities):
    s=identities;p=product(s,2,name='Catalogue label',sku='opaque');order(s,2,p,name='Hifancy Dream 45000 Puffs - Cola Ice')
    report=scan(s);body=auto_payload(report,{'2:2001:0'})
    r=s.call('/mapping-scans/'+report['id']+'/confirm','POST',body);assert r.status_code==202
    s.sql('DELETE FROM orders');s.work()
    result=s.call('/mapping-confirmations/'+r.get_json()['id']).get_json()
    assert result['status']=='failed' and not s.sql("SELECT * FROM inv_skus WHERE sku_code LIKE 'CAT-%'")


def test_remote_failure_creates_neither_master_nor_mapping(identities):
    s=identities;product(s,2);report=scan(s);body=auto_payload(report,{'2:2001:0'})
    s.http.fail_get=lambda url,kw:'target.test' in url
    result=confirm(s,report,body)
    assert result['status']=='failed' and not s.sql("SELECT * FROM inv_skus WHERE sku_code LIKE 'CAT-%'")
    assert not s.sql('SELECT * FROM inv_site_sku_map WHERE site_id=2')


@pytest.mark.parametrize('name,attribute', [
    ('Hifancy Dream 45000 Puffs', 'Smak'),
    ('Hifancy Dream 45K', 'Íz'),
    ('Hifancy Dream 45000', 'Příchuť'),
])
def test_localized_flavor_attributes_share_an_identity(identities, name, attribute):
    s=identities;product(s,1)
    p=product(s,2,name=name,sku='');p['attributes']=[{'name':attribute,'option':'COLA ICE'}]
    s.sql('DELETE FROM inv_site_sku_map WHERE wc_product_id=1001')
    report=scan(s);items=[i for i in report['items'] if i['id'] in ('1:1001:0','2:2001:0')]
    assert all(i['state']=='new' for i in items)
    assert items[0]['new_sku']['sku_code']==items[1]['new_sku']['sku_code']


def test_long_brand_alias_does_not_consume_model_and_pack_quantity_is_preserved(identities):
    s=identities
    s.sql("INSERT INTO brands VALUES(8,'Stag Bar',?)", (dumps(['Stagbar 6in1 180000 Puffs']),))
    s.sql("INSERT INTO brands VALUES(9,'FIZZY',?)", (dumps(['FIZZY TWINS']),))
    c=s.connect();rules=identity.classification_rules(c);c.close()
    assert identity.profile('Stagbar 6in1 180000 Puffs - Black Edition','',[],rules)['model_key']=='6in1'
    assert identity.profile('FIZZY TWINS 50000 Puffs - Cola Ice','',[],rules)['model_key']=='twins'
    single=identity.profile('Hifancy Dream 45000 Puffs - Cola Ice','',[],rules)
    pack=identity.profile('Hifancy Dream 45000 Puffs - Cola Ice (10 pcs)','',[],rules)
    assert pack['base_key']==single['base_key'] and pack['quantity']==10


def test_order_fallback_does_not_erase_unknown_variants_or_conflicting_strengths(identities):
    s=identities;p=product(s,2,name='Catalogue label',sku='opaque')
    p['attributes']=[{'name':'Color','option':'Blue'}]
    order(s,2,p,name='Hifancy Dream 45000 Puffs - Cola Ice')
    item=next(i for i in scan(s)['items'] if i['id']=='2:2001:0')
    assert not item.get('new_sku') and not item['certain']


def test_brand_alias_uncertainty_cannot_bypass_a_finite_inventory_sku(identities):
    s=identities
    s.sql("INSERT INTO brands VALUES(8,'FUMOT','[]')")
    s.sql("INSERT INTO brands VALUES(9,'RandM Tornado','[]')")
    s.sql("UPDATE inv_skus SET sku_code='FUMOT-15000',name='Fumot RandM Tornado 15000 Puffs - Cola Ice' WHERE id=1")
    s.sql('UPDATE oms_sku_warehouses SET warehouse_id=2 WHERE sku_id=1')
    s.sql('INSERT INTO inv_stock VALUES(2,1,25,0)')
    product(s,2,name='RandM Tornado 15000 Puffs - Cola Ice',sku='')
    item=next(i for i in scan(s)['items'] if i['id']=='2:2001:0')
    assert item['state']=='review' and not item.get('new_sku') and item['candidates']==[1]


def test_new_conflicting_order_after_preview_blocks_all_writes(identities):
    s=identities;p=product(s,2);order(s,2,p)
    report=scan(s);body=auto_payload(report,{'2:2001:0'})
    r=s.call('/mapping-scans/'+report['id']+'/confirm','POST',body);assert r.status_code==202
    order(s,2,p,name='Hifancy Dream 45000 Puffs - Strawberry Ice',sku='')
    s.work();result=s.call('/mapping-confirmations/'+r.get_json()['id']).get_json()
    assert result['status']=='failed' and not s.sql("SELECT * FROM inv_skus WHERE sku_code LIKE 'CAT-%'")


def test_alignment_revalidates_stock_and_keeps_the_original_mapping(identities):
    s=identities
    for k in (1,2):s.sql('UPDATE inv_skus SET sku_code=?,name=? WHERE id=?',(f'MANUAL-PL-{k}-1-1','Hifancy Dream 45000 Puffs - Cola Ice',k))
    product(s,1);s.sql('UPDATE inv_site_sku_map SET sku_id=2 WHERE wc_product_id=1001')
    report=scan(s);body=auto_payload(report,{'1:1001:0'})
    r=s.call('/mapping-scans/'+report['id']+'/confirm','POST',body);assert r.status_code==202
    s.sql('INSERT INTO inv_stock VALUES(1,2,10,0)');s.work()
    result=s.call('/mapping-confirmations/'+r.get_json()['id']).get_json()
    assert result['status']=='failed'
    assert s.sql('SELECT sku_id FROM inv_site_sku_map WHERE wc_product_id=1001')[0]['sku_id']==2
