"""Mapping assistance uses real API/worker/DB with synthetic Woo HTTP only."""
from datetime import timedelta
import os
import pytest

from stock_sync_fixtures import system
from stock_sync_common import dumps, stamp
import stock_sync_mapping


@pytest.fixture
def mapped_system(system):
    s = system; s.seed()
    s.sql('ALTER TABLE users ADD COLUMN can_manage_inventory BOOLEAN DEFAULT FALSE')
    for column, kind in [('brand_id','INTEGER'),('series_id','INTEGER'),('puff_count','INTEGER'),('flavor','TEXT'),('barcode','TEXT'),('unit','TEXT')]:
        s.sql(f'ALTER TABLE inv_skus ADD COLUMN {column} {kind}')
    s.sql('CREATE TABLE product_mappings(id INTEGER PRIMARY KEY,raw_name TEXT,source TEXT,brand_id INTEGER,series_id INTEGER,puff_count INTEGER,flavor TEXT)')
    s.sql('CREATE UNIQUE INDEX fixture_map_identity ON inv_site_sku_map(site_id,wc_product_id,wc_variation_id)')
    if os.getenv('STOCK_SYNC_TEST_POSTGRES') == '1':
        s.sql('ALTER TABLE inv_site_sku_map ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 100000)')
    s.sql('DELETE FROM inv_site_sku_map WHERE site_id=2')
    return s


def scan(s, source=1, targets=None):
    r = s.call('/mapping-scans','POST',{'source_site_id':source,'target_scope':{'mode':'explicit_sites','site_ids':targets or [2]}})
    assert r.status_code == 202, r.get_json()
    id_ = r.get_json()['id']; s.work()
    return s.call('/mapping-scans/'+id_).get_json()


def payload(report, count=1):
    items = [i for i in report['items'] if i['site_id']==2 and i['state'] in ('suggested','review','unmatched')][:count]
    return {'items':[{'id':i['id'],'sku_id':i['proposed_sku_id'] or 1,'qty_per_item':1} for i in items],
            'reason':'fixture reviewed binding','reviewed':True}


def confirm(s, report, body=None):
    r = s.call('/mapping-scans/'+report['id']+'/confirm','POST',body or payload(report))
    assert r.status_code == 202, r.get_json()
    s.work()
    return s.call('/mapping-confirmations/'+r.get_json()['id']).get_json()


def test_read_suggest_confirm_then_real_stock_preview_and_execution(mapped_system):
    s=mapped_system; report=scan(s)
    assert report['complete'] and report['counts']=={'mapped':3,'suggested':3}
    assert len(s.sql('SELECT * FROM inv_site_sku_map WHERE site_id=2')) == 0
    assert not s.http.puts
    result=confirm(s,report)
    assert result['status']=='complete' and result['counts']=={'saved':1}
    assert not s.http.puts
    assert len(s.sql("SELECT * FROM stock_sync_events WHERE kind='mapping_created'"))==1
    plan=s.plan('reference_status')
    assert plan['summary']['change']==1 and plan['summary']['skipped']==2
    result=s.execute(plan)
    assert result['status']=='succeeded' and len(s.http.puts)==1


def test_reuses_site_specific_classification_and_pack_quantity(mapped_system):
    s=mapped_system
    s.sql("UPDATE inv_skus SET brand_id=7,series_id=8,puff_count=10000,flavor='Blueberry',unit='pcs' WHERE id=1")
    product=s.http.products['https://target.test/wp-json/wc/v3/products/2001']
    product.update(name='Already classified local name',sku='')
    s.sql("INSERT INTO product_mappings VALUES(1,?,'https://target.test',7,8,10000,'Blueberry')",(product['name'],))
    report=scan(s); item=next(i for i in report['items'] if i['id']=='2:2001:0')
    assert item['proposed_sku_id']==1 and '复用已有' in item['explanation']
    assert not item['certain']
    body=payload(report);body['items'][0]['qty_per_item']=10
    assert confirm(s,report,body)['complete']
    assert s.sql('SELECT qty_per_item FROM inv_site_sku_map WHERE site_id=2')[0]['qty_per_item']==10
    assert not s.http.puts


def test_scoped_classification_does_not_use_another_sites_override(mapped_system):
    s=mapped_system
    s.http.products['https://target.test/wp-json/wc/v3/products/2001'].update(name='Same local name',sku='')
    s.sql("UPDATE inv_skus SET brand_id=7,puff_count=10000,flavor='Blueberry' WHERE id=1")
    s.sql("INSERT INTO product_mappings VALUES(1,'Same local name','https://outside.test',7,NULL,10000,'Blueberry')")
    item=next(i for i in scan(s)['items'] if i['id']=='2:2001:0')
    assert item['state']=='unmatched'


def test_settings_brand_alias_and_existing_name_parser_are_reused(mapped_system):
    s=mapped_system
    s.sql('CREATE TABLE brands(id INTEGER PRIMARY KEY,name TEXT,aliases TEXT)')
    s.sql('CREATE TABLE series(id INTEGER PRIMARY KEY,brand_id INTEGER,name TEXT)')
    s.sql('INSERT INTO brands VALUES(7,?,?)', ('Canonical Brand', dumps(['RecognizedAlias'])))
    s.sql("INSERT INTO series VALUES(8,7,'Blade')")
    s.sql("UPDATE inv_skus SET brand_id=7,series_id=8,puff_count=30000,flavor='Blueberry' WHERE id=1")
    s.http.products['https://target.test/wp-json/wc/v3/products/2001'].update(name='RecognizedAlias Blade 30 000 Puffs - Blueberry',sku='')
    report=scan(s);item=next(i for i in report['items'] if i['id']=='2:2001:0')
    assert item['proposed_sku_id']==1 and item['recognition']=={'brand_id':7,'series_id':8,'puff_count':30000,'flavor':'Blueberry'}
    s.sql("UPDATE brands SET aliases='[]' WHERE id=7")
    assert s.call('/mapping-scans/'+report['id']+'/confirm','POST',payload(report)).status_code==409


def test_duplicate_identifiers_and_ambiguous_recognition_require_review(mapped_system):
    s=mapped_system
    for pid in (2001,2002):s.http.products[f'https://target.test/wp-json/wc/v3/products/{pid}']['sku']='SKU-1'
    report=scan(s)
    assert all(not i['certain'] for i in report['items'] if i['id'] in ('2:2001:0','2:2002:0'))
    s.sql("UPDATE inv_skus SET brand_id=7,puff_count=10000,flavor='Blueberry' WHERE id IN (1,2)")
    s.http.products['https://target.test/wp-json/wc/v3/products/2001'].update(name='Translated',sku='')
    s.sql("INSERT INTO product_mappings VALUES(1,'Translated',NULL,7,NULL,10000,'Blueberry')")
    item=next(i for i in scan(s)['items'] if i['id']=='2:2001:0')
    assert item['state']=='review' and set(item['candidates'])=={1,2} and item['proposed_sku_id'] is None


def test_variation_marketing_title_matches_legacy_sku_without_changing_master(mapped_system):
    s=mapped_system
    s.sql('CREATE TABLE brands(id INTEGER PRIMARY KEY,name TEXT,aliases TEXT)')
    s.sql('CREATE TABLE series(id INTEGER PRIMARY KEY,brand_id INTEGER,name TEXT)')
    s.sql('INSERT INTO brands VALUES(7,?,?)', ('Canonical Brand', dumps(['RecognizedAlias'])))
    s.sql("INSERT INTO series VALUES(8,7,'Blade')")
    s.sql("UPDATE inv_skus SET name='Canonical Brand Blade 30000 Puffs - Blueberry' WHERE id=1")
    root='https://target.test/wp-json/wc/v3/products/2001'
    parent=s.http.products[root]
    parent.update(type='variable',variations=[2011],name='RecognizedAlias Blade 30000 Puffs – Bestseller | Screen 2.1 inch')
    s.http.products[root+'/variations/2011']=dict(parent,id=2011,type='variation',parent_id=2001,sku='',attributes=[{'name':'pa_smak','option':'Blueberry'}])
    item=next(i for i in scan(s)['items'] if i['id']=='2:2001:2011')
    assert item['state']=='suggested' and item['proposed_sku_id']==1 and item['certain']
    assert item['recognition']=={'brand_id':7,'series_id':8,'puff_count':30000,'flavor':'Blueberry'}
    assert s.sql('SELECT brand_id,series_id,puff_count,flavor FROM inv_skus WHERE id=1')[0]=={'brand_id':None,'series_id':None,'puff_count':None,'flavor':None}
    assert not s.http.puts


def test_multiple_flavor_attributes_are_not_resolved_by_title(mapped_system):
    s=mapped_system;root='https://target.test/wp-json/wc/v3/products/2001'
    parent=s.http.products[root];parent.update(type='variable',variations=[2011],name='Parent')
    s.http.products[root+'/variations/2011']=dict(parent,id=2011,type='variation',parent_id=2001,sku='SKU-1',attributes=[{'name':'pa_smak','option':'Blueberry'},{'name':'flavor','option':'Strawberry'}])
    item=next(i for i in scan(s)['items'] if i['id']=='2:2001:2011')
    assert item['state']=='review' and not item['certain'] and item['proposed_sku_id'] is None


def test_variation_ids_and_attribute_conflicts_are_preserved(mapped_system):
    s=mapped_system; root='https://target.test/wp-json/wc/v3/products/2001'
    parent=s.http.products[root];parent.update(type='variable',variations=[2011],name='Parent')
    leaf=dict(parent,id=2011,type='variation',parent_id=2001,sku='SKU-1',attributes=[{'name':'pa_smak','option':'Strawberry'}])
    s.http.products[root+'/variations/2011']=leaf
    s.sql("INSERT INTO product_mappings VALUES(1,'Parent',NULL,7,NULL,10000,'Blueberry')")
    report=scan(s);item=next(i for i in report['items'] if i['id']=='2:2001:2011')
    assert item['state']=='review' and not item['certain'] and '不同' in item['explanation']
    body={'items':[{'id':item['id'],'sku_id':2,'qty_per_item':1}],'reason':'reviewed flavour','reviewed':True}
    result=confirm(s,report,body)
    assert result['complete']
    assert s.sql('SELECT wc_product_id,wc_variation_id,sku_id FROM inv_site_sku_map WHERE site_id=2')[0]=={'wc_product_id':2001,'wc_variation_id':2011,'sku_id':2}


@pytest.mark.parametrize('kind',['sku','rule','product','site','permission'])
def test_queued_confirmation_rejects_changed_inputs_without_any_mapping(mapped_system,kind):
    s=mapped_system;report=scan(s)
    r=s.call('/mapping-scans/'+report['id']+'/confirm','POST',payload(report,2));assert r.status_code==202
    if kind=='sku':s.sql("UPDATE inv_skus SET name='Changed' WHERE id=1")
    if kind=='rule':s.sql("INSERT INTO product_mappings VALUES(1,'New',NULL,1,NULL,1,'Changed')")
    if kind=='product':s.http.products['https://target.test/wp-json/wc/v3/products/2002']['name']='Changed'
    if kind=='site':s.sql("UPDATE sites SET url='https://changed.test' WHERE id=2")
    if kind=='permission':s.sql('UPDATE users SET is_active=FALSE WHERE id=1')
    s.work()
    assert not s.sql('SELECT * FROM inv_site_sku_map WHERE site_id=2')
    assert s.sql('SELECT status FROM stock_sync_catalog_snapshots WHERE id=?',(r.get_json()['id'],))[0]['status']=='failed'
    assert not s.http.puts


def test_existing_conflict_rolls_back_entire_batch_and_never_overwrites(mapped_system):
    s=mapped_system;report=scan(s)
    r=s.call('/mapping-scans/'+report['id']+'/confirm','POST',payload(report,2))
    s.sql('INSERT INTO inv_site_sku_map VALUES(9000,2,2002,0,3,7,TRUE,NULL)')
    s.work()
    assert s.sql('SELECT wc_product_id,sku_id,qty_per_item FROM inv_site_sku_map WHERE site_id=2')==[{'wc_product_id':2002,'sku_id':3,'qty_per_item':7}]
    assert not s.sql("SELECT * FROM stock_sync_events WHERE kind='mapping_created'")
    assert s.call('/mapping-confirmations/'+r.get_json()['id']).get_json()['status']=='failed'


def test_duplicate_confirmation_is_idempotent(mapped_system):
    s=mapped_system;report=scan(s);body=payload(report,2)
    a=s.call('/mapping-scans/'+report['id']+'/confirm','POST',body)
    body['items'].reverse()
    b=s.call('/mapping-scans/'+report['id']+'/confirm','POST',body)
    assert a.status_code==b.status_code==202 and a.get_json()==b.get_json()
    s.work()
    assert s.call('/mapping-scans/'+report['id']+'/confirm','POST',body).get_json()==a.get_json()
    assert len(s.sql('SELECT * FROM inv_site_sku_map WHERE site_id=2'))==2
    assert len(s.sql("SELECT * FROM stock_sync_work WHERE kind='mapping_confirm'"))==1


def test_expiry_during_remote_verification_prevents_save(mapped_system,monkeypatch):
    s=mapped_system;report=scan(s)
    r=s.call('/mapping-scans/'+report['id']+'/confirm','POST',payload(report))
    real_now=stock_sync_mapping.now
    def advance(_url):
        monkeypatch.setattr(stock_sync_mapping,'now',lambda:real_now()+timedelta(hours=2))
    s.http.on_get=advance;s.work()
    assert s.call('/mapping-confirmations/'+r.get_json()['id']).get_json()['status']=='failed'
    assert not s.sql('SELECT * FROM inv_site_sku_map WHERE site_id=2')


@pytest.mark.parametrize('value',[0,-1,1.5,True,'1',100001])
def test_invalid_units_rejected(mapped_system,value):
    s=mapped_system;report=scan(s);body=payload(report);body['items'][0]['qty_per_item']=value
    assert s.call('/mapping-scans/'+report['id']+'/confirm','POST',body).status_code==400


def test_permissions_shared_reference_and_generic_route_isolation(mapped_system):
    s=mapped_system;s.login(2)
    assert s.call('/mapping-scans','POST',{'target_scope':{'mode':'explicit_sites','site_ids':[2]}}).status_code==403
    s.sql('UPDATE users SET can_manage_inventory=TRUE WHERE id=2')
    s.sql('INSERT INTO stock_sync_reference_sites VALUES(1,TRUE,1,1,?)',(stamp(),))
    s.sql('DELETE FROM inv_site_sku_map WHERE site_id=1')
    report=scan(s)
    source_item=next(i for i in report['items'] if i['site_id']==1)
    assert not source_item['writable']
    body=payload(report);body['items'][0]['id']=source_item['id']
    assert s.call('/mapping-scans/'+report['id']+'/confirm','POST',body).status_code==403
    assert s.call('/catalog-scans/'+report['id']).status_code==404
    assert s.call('/catalog-snapshots/'+report['id']+'/products').status_code==404
    s.login(3);s.sql('UPDATE users SET can_manage_inventory=TRUE WHERE id=3')
    assert s.call('/mapping-scans/'+report['id']).status_code==403
    s.login(2);s.sql('UPDATE users SET can_manage_inventory=FALSE WHERE id=2')
    assert s.call('/mapping-scans/'+report['id']).status_code==403


def test_incomplete_expired_and_unreviewed_snapshots_cannot_confirm(mapped_system):
    s=mapped_system;s.http.fail_get=lambda url,kw:'target.test' in url
    report=scan(s);assert report['status']=='failed' and not report['complete']
    assert s.call('/mapping-scans/'+report['id']+'/confirm','POST',{'reviewed':True}).status_code==409
    s.http.fail_get=None;report=scan(s);body=payload(report);body['reviewed']=False
    assert s.call('/mapping-scans/'+report['id']+'/confirm','POST',body).status_code==400
    body['reviewed']=True;s.sql('UPDATE stock_sync_catalog_snapshots SET expires_at=? WHERE id=?',(stamp(-1),report['id']))
    assert s.call('/mapping-scans/'+report['id']+'/confirm','POST',body).status_code==409


def test_mapping_requests_require_csrf_and_cannot_create_stock_plan(mapped_system):
    s=mapped_system
    assert s.client.post('/api/product-manager/stock-sync/mapping-scans',json={}).status_code==403
    report=scan(s)
    r=s.call('/plans','POST',{'operation':'reference_status','source_site_id':1,'reason':'test',
        'catalog_snapshot_id':report['id'],'selection':{'mode':'all'},'target_scope':{'mode':'explicit_sites','site_ids':[2]}})
    assert r.status_code==400
    html=s.client.get('/product-manager/stock-sync')
    assert html.status_code==200 and '读取并生成映射建议' in html.get_data(as_text=True)
