-- Durable synchronization state. PostgreSQL is authoritative; Redis only
-- transports bounded Celery messages.

SET ROLE woo_analysis_owner;
SET search_path TO public;

CREATE TABLE IF NOT EXISTS pg_schema_migrations (
    version text PRIMARY KEY,
    checksum text NOT NULL,
    applied_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sync_runs (
    run_id uuid PRIMARY KEY,
    mode text NOT NULL CHECK (mode IN ('quick','auto','deep')),
    status text NOT NULL CHECK (
        status IN (
            'queued','running','recovering','cancelling',
            'cancelled','success','error','interrupted'
        )
    ),
    created_by text,
    requested_params jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at timestamptz,
    heartbeat_at timestamptz,
    finished_at timestamptz,
    total_sites integer NOT NULL DEFAULT 0 CHECK (total_sites >= 0),
    completed_sites integer NOT NULL DEFAULT 0 CHECK (completed_sites >= 0),
    total_pages integer NOT NULL DEFAULT 0 CHECK (total_pages >= 0),
    completed_pages integer NOT NULL DEFAULT 0 CHECK (completed_pages >= 0),
    fetched_orders bigint NOT NULL DEFAULT 0 CHECK (fetched_orders >= 0),
    written_orders bigint NOT NULL DEFAULT 0 CHECK (written_orders >= 0),
    changed_orders bigint NOT NULL DEFAULT 0 CHECK (changed_orders >= 0),
    current_site_id bigint,
    error_message text,
    cancellation_requested boolean NOT NULL DEFAULT false,
    recovery_count integer NOT NULL DEFAULT 0 CHECK (recovery_count >= 0),
    version bigint NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_sync_runs_one_active
ON sync_runs ((1))
WHERE status IN ('queued','running','recovering','cancelling');

CREATE INDEX IF NOT EXISTS idx_sync_runs_created
ON sync_runs (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sync_runs_active_heartbeat
ON sync_runs (heartbeat_at)
WHERE status IN ('queued','running','recovering','cancelling');

CREATE TABLE IF NOT EXISTS sync_site_progress (
    run_id uuid NOT NULL REFERENCES sync_runs(run_id) ON DELETE CASCADE,
    site_id bigint NOT NULL REFERENCES sites(id) ON DELETE RESTRICT,
    status text NOT NULL CHECK (
        status IN (
            'queued','fetching','writing','recovering','cancelled',
            'success','error','auth_error'
        )
    ),
    fetch_after text,
    current_page integer NOT NULL DEFAULT 0 CHECK (current_page >= 0),
    total_pages integer NOT NULL DEFAULT 0 CHECK (total_pages >= 0),
    fetched_count bigint NOT NULL DEFAULT 0 CHECK (fetched_count >= 0),
    written_count bigint NOT NULL DEFAULT 0 CHECK (written_count >= 0),
    changed_count bigint NOT NULL DEFAULT 0 CHECK (changed_count >= 0),
    retry_count integer NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
    heartbeat_at timestamptz,
    started_at timestamptz,
    finished_at timestamptz,
    error_message text,
    last_content_hash text,
    version bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (run_id, site_id)
);

CREATE INDEX IF NOT EXISTS idx_sync_site_progress_status
ON sync_site_progress (run_id, status, site_id);

CREATE TABLE IF NOT EXISTS sync_page_dispatches (
    run_id uuid NOT NULL,
    site_id bigint NOT NULL,
    page integer NOT NULL CHECK (page > 0),
    status text NOT NULL CHECK (
        status IN (
            'queued','fetching','retry','fetched','writing',
            'completed','cancelled','error','auth_error'
        )
    ),
    fetch_task_id text,
    write_task_id text,
    fetch_attempts integer NOT NULL DEFAULT 0 CHECK (fetch_attempts >= 0),
    content_hash text,
    fetched_count integer NOT NULL DEFAULT 0 CHECK (fetched_count >= 0),
    heartbeat_at timestamptz,
    available_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    error_message text,
    PRIMARY KEY (run_id, site_id, page),
    FOREIGN KEY (run_id, site_id)
        REFERENCES sync_site_progress(run_id, site_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sync_page_dispatch_recovery
ON sync_page_dispatches (status, heartbeat_at, available_at);

CREATE TABLE IF NOT EXISTS sync_page_receipts (
    receipt_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id uuid NOT NULL,
    site_id bigint NOT NULL,
    page integer NOT NULL CHECK (page > 0),
    content_hash text NOT NULL,
    fetched_count integer NOT NULL CHECK (fetched_count >= 0),
    written_count integer NOT NULL CHECK (written_count >= 0),
    changed_count integer NOT NULL CHECK (changed_count >= 0),
    is_last_page boolean NOT NULL,
    committed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (run_id, site_id, page, content_hash),
    UNIQUE (run_id, site_id, page),
    FOREIGN KEY (run_id, site_id)
        REFERENCES sync_site_progress(run_id, site_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sync_page_receipts_progress
ON sync_page_receipts (run_id, site_id, page);

CREATE TABLE IF NOT EXISTS sync_task_outbox (
    outbox_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dedupe_key text NOT NULL UNIQUE,
    queue_name text NOT NULL CHECK (queue_name IN ('sync_fetch','sync_write')),
    task_name text NOT NULL,
    payload jsonb NOT NULL,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending','publishing','published','error','cancelled')),
    celery_task_id text,
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    available_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error text
);

CREATE INDEX IF NOT EXISTS idx_sync_task_outbox_pending
ON sync_task_outbox (available_at, outbox_id)
WHERE status IN ('pending','error');

CREATE TABLE IF NOT EXISTS sync_events (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id uuid NOT NULL REFERENCES sync_runs(run_id) ON DELETE CASCADE,
    site_id bigint,
    level text NOT NULL DEFAULT 'info'
        CHECK (level IN ('debug','info','warning','error')),
    event_type text NOT NULL,
    message text NOT NULL,
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sync_events_run
ON sync_events (run_id, event_id);

CREATE TABLE IF NOT EXISTS external_operations (
    operation_id uuid PRIMARY KEY,
    operation_type text NOT NULL,
    idempotency_key text NOT NULL UNIQUE,
    order_id text NOT NULL,
    site_id bigint REFERENCES sites(id) ON DELETE RESTRICT,
    request_hash text NOT NULL,
    request_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL CHECK (
        status IN (
            'pending','external_success','local_committed','notified',
            'reconciliation_required','failed','cancelled'
        )
    ),
    external_reference text,
    external_evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    created_by text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    external_succeeded_at timestamptz,
    local_committed_at timestamptz,
    notified_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error text
);

CREATE INDEX IF NOT EXISTS idx_external_operations_reconcile
ON external_operations (status, updated_at)
WHERE status IN ('pending','external_success','reconciliation_required');

-- Celery Beat checks database-backed settings every minute.  Do not insert
-- defaults here: migration verification requires every legacy table to retain
-- the exact SQLite row set.  The scheduler and settings API use the audited
-- 03:30 deep-sync defaults until an administrator explicitly saves them.

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public
TO woo_analysis_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public
TO woo_analysis_app;

RESET ROLE;
